# Generated by Django 3.1.7 on 2021-04-03 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('po', '0001_initial'),
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.IntegerField(default=0)),
                ('user_id', models.CharField(blank=True, default='', max_length=15)),
                ('cc_id_link', models.CharField(blank=True, default='', max_length=23)),
                ('transaction_date', models.DateField()),
                ('vendor', models.CharField(default='', max_length=50)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('ro1', models.IntegerField(blank=True, default=0, null=True)),
                ('ro2', models.IntegerField(blank=True, default=0, null=True)),
                ('ro3', models.IntegerField(blank=True, default=0, null=True)),
                ('ro4', models.IntegerField(blank=True, default=0, null=True)),
                ('ro5', models.IntegerField(blank=True, default=0, null=True)),
                ('invoice', models.CharField(blank=True, default='', max_length=20)),
                ('returned', models.BooleanField(default=False)),
                ('credit', models.BooleanField(default=False)),
                ('voided', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('po_cost', models.FloatField(blank=True, null=True)),
                ('po_price', models.FloatField(blank=True, null=True)),
                ('start', models.IntegerField(default=0)),
                ('stop', models.IntegerField(default=0)),
                ('cc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc.ccm')),
                ('po', models.ManyToManyField(blank=True, null=True, to='po.PO')),
            ],
        ),
    ]
