# Generated by Django 3.1.7 on 2021-03-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CC_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.IntegerField(default=0)),
                ('user_id', models.CharField(blank=True, default='', max_length=15)),
                ('cc_id', models.CharField(blank=True, default='', max_length=23)),
                ('transaction_date', models.DateField()),
                ('vendor', models.CharField(default='', max_length=50)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('ro1', models.IntegerField(blank=True, default=0, null=True)),
                ('ro2', models.IntegerField(blank=True, default=0, null=True)),
                ('ro3', models.IntegerField(blank=True, default=0, null=True)),
                ('ro4', models.IntegerField(blank=True, default=0, null=True)),
                ('ro5', models.IntegerField(blank=True, default=0, null=True)),
                ('invoice', models.CharField(blank=True, default='', max_length=20)),
                ('returned', models.BooleanField(default=False)),
                ('credit', models.BooleanField(default=False)),
                ('voided', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('start', models.IntegerField(default=0)),
                ('stop', models.IntegerField(default=0)),
            ],
        ),
    ]
