# Generated by Django 3.2.5 on 2021-09-21 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cclog', '0002_auto_20210920_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='cc_id',
            new_name='cc_id_key',
        ),
    ]
