# Generated by Django 3.2.5 on 2021-09-22 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cclog', '0003_rename_cc_id_log_cc_id_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='cc_id_link',
            new_name='cc_id',
        ),
    ]
