# Generated by Django 3.2.5 on 2021-09-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cclog', '0004_rename_cc_id_link_log_cc_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='vendor_id',
            new_name='vendor_id_key',
        ),
    ]
