# Generated by Django 3.2.5 on 2021-09-22 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cclog', '0005_rename_vendor_id_log_vendor_id_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='vendor_id_link',
            new_name='vendor_id',
        ),
    ]
