# Generated by Django 3.1.7 on 2021-04-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCm',
            fields=[
                ('cc_id', models.CharField(max_length=23, primary_key=True, serialize=False)),
                ('up_id', models.CharField(default='', max_length=15)),
                ('user_id', models.CharField(blank=True, default='', max_length=15)),
                ('claim_timestamp', models.IntegerField(default=0)),
                ('posted_date', models.CharField(max_length=10)),
                ('payee', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('log_id', models.IntegerField(default=0)),
                ('ro', models.CharField(blank=True, default='', max_length=100)),
                ('invoice', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
    ]
