# Generated by Django 3.2.5 on 2021-09-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_ccm_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccm',
            name='posted_date',
            field=models.DateField(),
        ),
    ]
